version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./pg_data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  cache:
    image: redis
    ports:
      - 6379:6379

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080
